name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install depedencies
        run: npm ci
        working-directory: server

      - name: Run our unit tests
        run: npm test
        working-directory: server
